### ISSUE TITLE
API requests fired on initial load against 127.0.0.1:80

### ISSUE THREAD

**Issue by strues** [strues/boldr#226]
Unable to find any rhyme or reason to why this happens. I'm able to reproduce it in other projects. Common denominator seems to be redux-connect
```
error:
      { Error: connect ECONNREFUSED 127.0.0.1:80
          at Object.exports._errnoException (util.js:1022:11)
          at exports._exceptionWithHostPort (util.js:1045:20)
          at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
        code: 'ECONNREFUSED',
        errno: 'ECONNREFUSED',
        syscall: 'connect',
        address: '127.0.0.1',
        port: 80,
        response: undefined },
```

**Comment by strues** [comment]
Solved in #226
