### ISSUE TITLE
Code Organization

### ISSUE THREAD

**Issue by cloudkompute** [strues/boldr#309]
I want to learn from this project. I can't understand why there are 4 different packages each having its own package.json. Usually, a project has two: one for Web PAck development server and the second for API server.

I am also curious to know about the state of the project. Is it complete, or development is suspended, or the  main contributor is working on any other branch? Can we use the code in a production environment?

**Comment by strues** [comment]
Hey @coooolers sorry I've been busy. I'll make time tomorrow morning to tidy up and write a detailed overview.

**Comment by cloudkompute** [comment]
Thank you. Also pl. mention how to install it locally. I followed these steps but was not successful.

*Run the frontend using yr dev from within packages/frontend. In another terminal window, start the server using yr dev from within packages/server.*

**Comment by cloudkompute** [comment]
Can you pl. update the Overview and write the steps to install and run the program.

**Comment by strues** [comment]
All set https://github.com/strues/boldr/blob/develop/docs/setup.md

**Comment by cloudkompute** [comment]
Thanks.. But there is no folder by the name 'project' and this directory structure is not available in any of the folders..

The main application currently lives in project.
The frontend and the react server entrypoint are located in project/src.
The actual server resides in project/server.

Copy the environment file sample. Use the command cd project && cp .env_example .env

**Comment by cloudkompute** [comment]
/Project/boldr/project$ yarn seed
yarn run v1.2.0
$ boldr seed
module.js:491
    throw err;
    ^

Error: Cannot find module '../lib/cli.js'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/cool/Project/boldr/packages/cli/bin/boldr.js:2:1)
**

In packages/bin/boldr.js
#!/usr/bin/env node
require('../lib/cli.js');

**Comment by cloudkompute** [comment]
How to handle this error, could you pl. answer?

Thx

**Comment by cloudkompute** [comment]
Could you pl. help solve this error, it is preventing me to use this package ..

$ boldr seed
module.js:491
throw err;
^

Error: Cannot find module '../lib/cli.js'

**Comment by cloudkompute** [comment]
Could you pl. help resolve this issue.. Thanks
