### ISSUE TITLE
Runtime Error: TypeError: Cannot read property 'role' of undefined

### ISSUE THREAD

**Issue by cloudcompute** [strues/boldr#42]
TypeError: Cannot read property 'role' of undefined
   at boldrSSR (/home/sunny/Projects/boldr/build/server/webpack:/src/server/ssr/boldrSSR.js:46:15)
   at Layer.handle [as handle_request](/home/sunny/Projects/boldr/node_modules/express/lib/router/layer.js:95:5)
   at next (/home/sunny/Projects/boldr/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/home/sunny/Projects/boldr/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request](/home/sunny/Projects/boldr/node_modules/express/lib/router/layer.js:95:5)
   at /home/sunny/Projects/boldr/node_modules/express/lib/router/index.js:277:22
   at param (/home/sunny/Projects/boldr/node_modules/express/lib/router/index.js:349:14)
   at param (/home/sunny/Projects/boldr/node_modules/express/lib/router/index.js:365:14)
   at Function.process_params (/home/sunny/Projects/boldr/node_modules/express/lib/router/index.js:410:3)
   at next (/home/sunny/Projects/boldr/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle [as handle_request](/home/sunny/Projects/boldr/node_modules/express/lib/router/layer.js:91:12)
   at trim_prefix (/home/sunny/Projects/boldr/node_modules/express/lib/router/index.js:312:13)
   at /home/sunny/Projects/boldr/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/home/sunny/Projects/boldr/node_modules/express/lib/router/index.js:330:12)
   at next (/home/sunny/Projects/boldr/node_modules/express/lib/router/index.js:271:10)
   at /home/sunny/Projects/boldr/build/server/webpack:/src/server/middleware/index.js:94:5

**Comment by cloudcompute** [comment]
When I did npm run start:dev the logs indicated that the client and server are running. 

7/11/2016, 3:53:26 PM - info: ==> HTTP Listener is running on port 3000

But it didn't auto-load the localhost:3000 page. So when I did it manually, the error was:  TypeError: Cannot read property 'role' of undefined

**Comment by strues** [comment]
That should no longer be an issue happening on the latest in the development branch.

**Comment by cloudcompute** [comment]
Could you pl. upload the latest code? I am just relying on this package.

**Comment by cloudcompute** [comment]
By upload, I mean to say upload the stable code to the master branch. Thx.
